INSERT INTO combustion_engines (name, fuel_type, hp, cc, is_on) VALUES ('Ford V8', 'gasolina', 300, 3500, false)
INSERT INTO combustion_engines (name, fuel_type, hp, cc, is_on) VALUES ('Ford V4', 'gasolina', 150, 1900, false)
INSERT INTO combustion_engines (name, fuel_type, hp, cc, is_on) VALUES ('Renault S-512', 'diesel', 110, 1600, false)
INSERT INTO combustion_engines (name, fuel_type, hp, cc, is_on) VALUES ('Renault S-502', 'gasolina', 110, 1400, false)
INSERT INTO combustion_engines (name, fuel_type, hp, cc, is_on) VALUES ('Volvo A32', 'diesel', 70, 1200, false)
INSERT INTO combustion_engines (name, fuel_type, hp, cc, is_on) VALUES ('Volvo B50', 'gasolina', 125, 1600, false)

INSERT INTO electric_engines (name, hp, power, is_on) VALUES ('Ford Ion4', 70, 125, false)
INSERT INTO electric_engines (name, hp, power, is_on) VALUES ('Ford Flash', 125, 220, false)
INSERT INTO electric_engines (name, hp, power, is_on) VALUES ('Renault Sio', 125, 220, false)
INSERT INTO electric_engines (name, hp, power, is_on) VALUES ('Renault Flux', 125, 220, false)
INSERT INTO electric_engines (name, hp, power, is_on) VALUES ('Volvo Azr', 90, 125, false)
INSERT INTO electric_engines (name, hp, power, is_on) VALUES ('Volvo Arf', 65, 220, false)